name: "Verify"
on: [push]
env:
  NETCORE_VERSION: '3.1.101'                    # set this to the .NET Core version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore packages
        run: dotnet restore

      - name: Build app
        run: dotnet build --configuration Release --no-restore

      - name: Test app
        run: dotnet test --configuration Release --no-build

      - name: Bench
        run: dotnet run -c Release -p src/recursion.Bench/recursion.Bench.csproj